import type { Metadata } from 'next';
import RootFooter from '@/components/Footer/RootFooter';
import RootHeader from '@/components/Header/RootHeader';

export const metadata: Metadata = {
  title: { template: 'iBridge - %s', default: 'iBridge' },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <RootHeader />
        {children}
        <RootFooter />
      </body>
    </html>
  );
}
