import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home',
};

export default function Home() {
  return (
    <main>
      <h1>Welcome to Create Next App</h1>
      <p>Generated by create next app</p>
    </main>
  );
}
