// app/layout.tsx
import '../../globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Your App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className="flex flex-col min-h-screen">
        <main className="flex-grow">{children}</main>
        <footer className="bg-gray-200 text-white text-center py-8">
          ⓒ 2025 i-Bridge.   All rights reserved.
        </footer>
      </body>
    </html>
  )
}
